name: Cleanup

on:
  workflow_run:
    workflows: ['Deploy', 'Deploy debug']
    types:
      - completed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Prune
        uses: vlaurin/action-ghcr-prune@main
        with:
          token: ${{ secrets.PAT }}
          container: docker-znc
          dry-run: false
          untagged: true
