name: Cleanup

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '7 11 * * *'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Prune
        uses: vlaurin/action-ghcr-prune@main
        with:
          token: ${{ secrets.PAT }}
          container: docker-znc
          dry-run: false
          untagged: true
